import Foundation

private struct PackageMetadata: Decodable {
    let version: String
}

@main
struct GenerateIMessageCLIVersion {
    static func main() throws {
        guard CommandLine.arguments.count == 3 else {
            throw GeneratorError("usage: GenerateIMessageCLIVersion PACKAGE_JSON OUTPUT_SWIFT")
        }

        let packageJSONURL = URL(fileURLWithPath: CommandLine.arguments[1])
        let outputURL = URL(fileURLWithPath: CommandLine.arguments[2])
        let packageData = try Data(contentsOf: packageJSONURL)
        let metadata = try JSONDecoder().decode(PackageMetadata.self, from: packageData)

        try FileManager.default.createDirectory(
            at: outputURL.deletingLastPathComponent(),
            withIntermediateDirectories: true
        )
        try source(version: metadata.version).write(to: outputURL, atomically: true, encoding: .utf8)
    }

    private static func source(version: String) -> String {
        """
        // Generated by GenerateIMessageCLIVersionPlugin. Do not edit by hand.

        enum IMessageCLIVersion {
            static let packageVersion = \(String(reflecting: version))
        }
        """
    }
}

private struct GeneratorError: Error, CustomStringConvertible {
    let description: String

    init(_ description: String) {
        self.description = description
    }
}
