// This is generated by running `cbindgen` in `src/rust/RustServer`.

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef const char *rs_token_t;

typedef char *rs_token_mut_t;

rs_token_t rs_hash_thread_id(const char *thread_id);

const char *rs_original_thread_id(rs_token_t token);

void rs_free_token(rs_token_mut_t token);
