name: CI/CD

on:
  push:
  workflow_dispatch:
    inputs:
      publishing:
        description: 'Try to `npm publish` after building'
        required: true
        default: false
        type: boolean

jobs:
  check-version:
    runs-on: ubuntu-latest
    outputs:
      version_changed: ${{ steps.check.outputs.changed }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Check for version change
        id: check
        # Check to see if the line containing `"version":` was touched between
        # the current commit and the one before.
        run: |
          git diff @^ @ --name-only | grep "package.json" && \
          git diff @^ @ package.json | grep "\"version\":" && \
          echo "changed=true" >> $GITHUB_OUTPUT || echo "changed=false" >> $GITHUB_OUTPUT

  build:
    needs: check-version
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Xcode 16.2
        run: sudo xcode-select -s /Applications/Xcode_16.2.app

      - name: Inject access tokens
        shell: bash
        run: |
          git config --global url."https://oauth2:${{ secrets.BEEPER_DEPS_TOKEN }}@github.com/beeper/".insteadOf "https://github.com/beeper/"

      - name: Set up Rust toolchains
        run: |
          rustup toolchain install stable --profile minimal
          rustup target add x86_64-apple-darwin

      - uses: actions/setup-node@v4
        with:
          cache: 'yarn'

      - name: Cache Turborepo
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Install Node.js dependencies
        run: yarn install --immutable --inline-builds

        # NOTE(skip): Hopefully helps with caching.
        # See: https://michalzaborowski.medium.com/circleci-60-faster-builds-use-xcode-deriveddata-for-caching-96fb9a58930
      - name: Make Xcode amenable to cached derived data
        run: |
          defaults write com.apple.dt.XCBuild IgnoreFileSystemDeviceInodeChanges -bool YES

      - name: Build without publishing
        # We only want to publish if we're on the `main` branch and the version changed.
        # Otherwise, just build to provide diagnostics.
        # NOTE: Doing == 'true' because GitHub Actions doesn't coerce 'false' to false.
        if: ${{ !(github.ref_name == 'main' && needs.check-version.outputs.version_changed == 'true') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn build

      - name: Build and publish
        if: ${{ github.ref_name == 'main' && needs.check-version.outputs.version_changed == 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm publish
