name: CI/CD

on:
  push:
  workflow_dispatch:
    inputs:
      publishing:
        description: 'Try to `npm publish` after building'
        required: true
        default: false
        type: boolean

jobs:
  check-published:
    runs-on: ubuntu-latest
    outputs:
      version-exists: ${{ steps.check.outputs.version-exists }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Check if version has been published
        id: check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -eux -o pipefail
          version="$(jq -r .version package.json)"
          version_exists="$(npm show "@beeper/platform-imessage@$version" >/dev/null 2>&1 && echo true || echo false)"
          echo "version-exists=$version_exists" >> $GITHUB_OUTPUT

  build:
    needs: check-published
    runs-on: macos-15 # needed for Xcode 16.3 (required)

    steps:
      - uses: actions/checkout@v4

      - name: Download and install Xcode 26.1.1
        shell: bash
        run: |
          ver="26.1.1"
          xcodes install "$ver"
          xcodes select "$ver"

      - name: Inject access tokens
        shell: bash
        run: |
          git config --global url."https://oauth2:${{ secrets.BEEPER_DEPS_TOKEN }}@github.com/beeper/".insteadOf "https://github.com/beeper/"

      - uses: actions/setup-node@v4
        with:
          cache: 'yarn'

      - name: Cache Turborepo
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Install Node.js dependencies
        run: yarn install --immutable --inline-builds

        # NOTE(skip): Hopefully helps with caching.
        # See: https://michalzaborowski.medium.com/circleci-60-faster-builds-use-xcode-deriveddata-for-caching-96fb9a58930
      - name: Make Xcode amenable to cached derived data
        run: |
          defaults write com.apple.dt.XCBuild IgnoreFileSystemDeviceInodeChanges -bool YES

      - name: Build without publishing
        # We only want to publish if we're on the `main` branch and the version changed.
        # Otherwise, just build to provide diagnostics.
        if: ${{ !(github.ref_name == 'main' && (needs.check-published.outputs.version-exists == 'false' || inputs.publishing == 'true')) }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          CI_PUBLISHING: 'false'
        run: yarn build

      - name: Build and publish
        if: ${{ github.ref_name == 'main' && (needs.check-published.outputs.version-exists == 'false' || inputs.publishing == 'true') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          CI_PUBLISHING: 'true'
        # runs `prepack` which runs `yarn build` which runs `src/SwiftServer/build-swift.ts`
        run: npm publish
